# @package _global_
dmodel:

  pretrain_init_model_path: ""

  model:
    _partial_: True
    _target_: "robot_model.cartpole.cartpole_nn_model.CartPoleNNdynamics"
    
    preprocessor:
      _target_: "robot_model.cartpole.state_preprocesor.CartPoleStateAndCtrlPreprocessor"
      max_abs_x1: 40.0
      max_v1: 20.0
      max_dtheta: 20.0
      max_force: 20.0
    
    layer_sizes: [5, '${hpm.mlp_size}', 2]

    activation: 
      _target_: "torch.nn.Tanh"
    
    compile_model: ${hpm.compile}

    device: ${hpm.device}
