# @package _global_

dmodel:

  pretrain_init_model_path: ""

  model:
    _partial_: True
    _target_: "robot_model.drone.drone_residual.DroneResidualDynamisc"
    only_forces_regres_params: True
    layers_size: [10, 32, 6]
    device: ${hpm.device}
