# @package _global_
hmodel:
  model:
    time_series_encoder:
      _target_: "hyper_prediction_models.rnn_time_series_encoder.RnnTimeSeriesEncoder"

      observations_preprocessor: ${dataset.observations_preprocessor}

      observarions_channels: ${dataset.observarions_channels}
      time_series_latent_size: ${hmodel.time_series_laten_size}
      rnn_layers: 1
      rnn_cell: "lstm"
      compile_model: False
      device: ${hpm.device} 