# @package _global_
hmodel:

  time_series_laten_size: 8

  model:
    _partial_: True

    _target_: "hyper_prediction_models.rnn_decoder_hyper_model.GruDecoderHyperModel"

    # time_series_encoder from file

    future_prediction_encoder:
      _target_: "hyper_prediction_models.future_prediction_encoder.FuturePredictionEncoder"
      channels_count: 2 # FIXME get from dataset
      input_len: ${dataset.prediction_horizon}
      output_ctrl_point: ${hmodel.model.param_ctrl_point} 
      return_spline_and_error: False
      device: ${hpm.device}
    
    pred_noise_sigma: 0.05

    # default params <- partial

    activation:
      _target_: "torch.nn.Tanh"
    
    hp_size: 16

    predictions_botteckleneck_size: 2

    param_ctrl_point: 8

    max_param_scaler: 0.5
    
    last_ctrl_point_on_const: True

    # enable_prediction_head: True

    # always_positive: argumement get from dmodel
    
    compile_model: ${hpm.compile}
    device: ${hpm.device} 
  
  interpoler:
    _target_: "hyper_prediction_models.spline_param_interpolation.SplineParamInterpolation"
    param_ctrl_point: ${hmodel.model.param_ctrl_point}
    prediction_horizon: ${dataset.prediction_horizon}
    last_ctrl_point_on_const: ${hmodel.model.last_ctrl_point_on_const}
    integration_method: ${hpm.integration_method}
    compile_model: ${hpm.compile}
    device: ${hpm.device} 
  