# @package _global_
hmodel:

  time_series_laten_size: 8

  model:
    _partial_: True

    _target_: "hyper_prediction_models.rnn_hyper_model.HyperModel"

    # time_series_encoder from file
      
    # default params <- partial

    activation:
      _target_: "torch.nn.Tanh"
    middle_layer_size: 64
    param_ctrl_point: 8
    max_param_scaler: 0.25
    last_ctrl_point_on_const: True

    # always_positive: True
    
    compile_model: ${hpm.compile}
    device: ${hpm.device}    
  
  interpoler:
    _target_: "hyper_prediction_models.spline_param_interpolation.SplineParamInterpolation"
    param_ctrl_point: ${hmodel.model.param_ctrl_point}
    prediction_horizon: ${dataset.prediction_horizon}
    last_ctrl_point_on_const: ${hmodel.model.last_ctrl_point_on_const}
    integration_method: ${hpm.integration_method}
    compile_model: ${hpm.compile}
    device: ${hpm.device} 
  